services:
  - type: web
    name: zerodha-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: MONGO_URL
        sync: false

  - type: web
    name: zerodha-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    plan: free

  - type: web
    name: zerodha-dashboard
    runtime: static
    rootDir: dashboard
    buildCommand: npm install && npm run build
    staticPublishPath: build
    plan: free